---
apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  labels:
    app: example-pod
spec:
  containers:
  - name: rest-server
    image: dpetty20/cs370project:server_v1
    imagePullPolicy: Always
    ports:
    - containerPort: 4000
  - name: rest-client
    image: dpetty20/cs370project:client_v1
    imagePullPolicy: Always
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    app: example-service
spec:
  type: NodePort
  selector:
    app: example-pod
  ports:
  - name: http
    protocol: TCP
    targetPort: 4000
    port: 80
    nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: example-service2
  labels:
    app: example-service2
spec:
  type: NodePort
  selector:
    app: example-pod
  ports:
  - name: http
    protocol: TCP
    targetPort: 3000
    port: 80
    nodePort: 30002
